### ISSUE TITLE
No support for UNICODE in control files

### ISSUE THREAD

**Issue by fisselsker** [coherentgraphics/cpdf-binaries#20] opened 2017-09-25 22:33 UTC
I have a file in whose filename the UNICODE characters U+0069 (latin small letter i) and U+0301 (combining acute accent) appear consecutively. However, no matter what encoding I try, cpdf keeps reporting that the file doesn't exist. I've even tried encoding the control file as ISO-8859-1 or Windows-1252, except for the part constituting the filename, which was encoded as UTF-8, but it still doesn't work. Furthermore, the _-add-text_ command, which I use to add the filename to the pages, doesn't work properly, either. It does write the U+0069 (latin small letter i) when the control file is encoded with the weird combination of UTF-8 for the part constituting the text to be written and ISO-8859-1 for the remaining part, but the U+0301 (combining acute accent) is for some reason omitted. I think it would make a lot more sense if the control file was simply interpreted as being encoded with UTF-8 instead of this confusing combination of encodings that only work halfway anyway.

System details: Windows 7 Ultimate x64

Some examples of control files and corresponding results (I = ISO-8859-1 encoded; U= UTF-8 encoded):

`-add-text "test.pdf" "test.pdf" -o "out.pdf"`
`IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII`
Works great!

`-add-text "año.pdf" "año.pdf" -o "out.pdf"`
`IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII`
ERROR: Bad UTF8 in codepoints_of_utf8

`-add-text "año.pdf" "año.pdf" -o "out.pdf"`
`IIIIIIIIIIIUUUUUUUIIIIIIIIIIIIIIIIIIIIIIII`
Works great!

`-add-text "ahí.pdf" "año.pdf" -o "out.pdf"`
`IIIIIIIIIIIUUUUUUUIIIIIIIIIIIIIIIIIIIIIIII`
Partially working, U+0301 (combining acute accent) is omitted. NOTE: "í" is NOT the character "í" (latin small letter i with acute (U+00ED)) that can be typed using the keyboard!

`-add-text "ahí.pdf" "ahí.pdf" -o "out.pdf"`
`IIIIIIIIIIIUUUUUUUIIIIIIIIIIIIIIIIIIIIIIII`
ERROR: No such file or directory

`-add-text "ahí.pdf" "ahí.pdf" -o "out.pdf"`
`IIIIIIIIIIIUUUUUUUIIIUUUUUUUIIIIIIIIIIIIII`
ERROR: No such file or directory

**Comment by johnwhitington** [comment] 2017-09-26 10:57
The Windows port of cpdf can't cope with files with unicode filenames, either on the command line or in control files. This limitation is caused by the underlying language toolchain, but it has been fixed upstream, and so this should be fixed for the next version of cpdf.

As to adding unicode text using -add-text, this only works where the unicode codepoint represents a character available in the Latin1 encoding used by the standard 14 postscript/PDF fonts in use.

Control files are, so far as I can see from a quick look at the code, assumed to be UTF8 throughout.

Cpdf knows nothing about Windows-1252 at all.

I hope these comments allow you to make some progress...

**Comment by tmmlsBE** [comment] 2018-07-05 15:40
Hi, 
Any updates on this issue? I'm having the same issues adding text to a pdf with some foreign characters... 
Thankx

**Comment by johnwhitington** [comment] 2018-07-05 18:23
The text has foreign characters, or the filename?

**Comment by tmmlsBE** [comment] 2018-07-06 16:59
In the text....

**Comment by johnwhitington** [comment] 2018-07-06 17:04
cpdf uses the standard 14 adobe fonts. If the special character you are using exists in the Latin1 encoding, used by these fonts, you should have no problems. If it does not, there is nothing cpdf can do.

Can you supply an example?

**Comment by majkaz** [comment] 2019-01-21 14:17
I have the same error from command line but it is working from a control file: 

I am trying to add text "Souhlasíme s textem bankovní záruky". The accented characters are present in Latin1 but I am getting this error and the text is inserted as "Souhlas", missing the remaining part when run from cygwin (mintty), and completely missing when run from Windows command line.

Using UTF8 encoded control file with exact the same parameters works fine from either. However, I am getting error with UTF8-BOM.

**Comment by tmmlsBE** [comment] 2019-01-21 14:49
Hi majkaz. We solved this issue some time ago by converting the text to an octal String (http://www.unit-conversion.info/texttools/octal/). Don't forget to escape the octal values... I hope this helps ...

**Comment by johnwhitington** [comment] 2019-06-30 12:01
Cpdf 2.3 will support unicode filenames by default, so I am closing this for now.

**Comment by johnwhitington** [comment] 2019-06-30 12:01
> I am trying to add text "Souhlasíme s textem bankovní záruky". The accented characters are present in Latin1 but I am getting this error and the text is inserted as "Souhlas", missing the remaining part when run from cygwin (mintty), and completely missing when run from Windows command line.

This looks like a quoting problem on your command line, not a cpdf problem. The command line hits the accented character and thinks the string has ended....

**Comment by johnwhitington** [comment] 2019-06-30 12:03
Anyone on this thread is welcome to reopen when version 2.3 is released if they still have problems.

**Closed by johnwhitington** 2019-06-30 12:03 UTC
Labels: v2.3
